apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-site2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-deploy-81
  template:
    metadata:
      labels:
        app: ng-deploy-81
    spec:
      containers:
      - name: ng-deploy-81
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/pool1
          name: my-nfs-volume-pool1
        - mountPath: /usr/share/nginx/html/pool2
          name: my-nfs-volume-pool2
        - mountPath: /etc/localtime
          name: timefile
      volumes:
      - name: my-nfs-volume-pool1
        nfs:
          server: 192.168.211.90
          path: /data/k8sdata/pool1
      - name: my-nfs-volume-pool2
        nfs:
          server: 192.168.211.90
          path: /data/k8sdata/pool2
      - name: timefile
        hostPath:
          path: /etc/localtime


---
apiVersion: v1
kind: Service
metadata:
  name: ng-deploy-81
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30017
    protocol: TCP
  type: NodePort
  selector:
    app: ng-deploy-81